### ISSUE TITLE
Evaluation job crashes with "KeyError: eval_info" when submitted

### ISSUE THREAD

**Issue by NimaBoscarino** [huggingface/model-evaluator#69]
I’m trying to follow the [original announcement blog post](https://huggingface.co/blog/eval-on-the-hub), but when I try to run an evaluation on a model I’m getting the error in the screenshot. With some snooping, I see that during the filtering process `get_evaluation_infos` is fetching all the `autoevaluate` datasets, and then crashing when the first one’s ([lewtun/autoevaluate__imdb](https://huggingface.co/datasets/lewtun/autoevaluate__imdb)) `cardData` doesn’t have an `eval_info` property.

![image](https://user-images.githubusercontent.com/6765188/193682344-9396107d-08ff-477b-b639-9a107729d0be.png)

**Comment by lewtun** [comment]
Thanks for reporting! The `lewtun/autoevaluate__xxx` datasets were dummy ones from early testing and have now been removed. Closing this since the issue seems to be fixed, but feel free to re-open if you have troubles still :)

**Comment by AntoineBlanot** [comment]
Hello ! 
I am having the same issue when I want to evaluate my model (AntoineBlanot/roberta-large-squadv2) on squad_v2 dataset when using the model-evaluator. 
How can this issue be fixed?
